"""main muscle

Revision ID: 4521ffba0ae6
Revises: 6bbc794bf754
Create Date: 2025-03-12 14:28:40.763481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4521ffba0ae6'
down_revision = '6bbc794bf754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_muscle', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('main_muscle')

    # ### end Alembic commands ###
