"""removed enum

Revision ID: 9b975df4edff
Revises: 939df1cd3a9a
Create Date: 2025-03-16 22:30:40.822760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b975df4edff'
down_revision = '939df1cd3a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=mysql.ENUM('kg, lbs'),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.String(length=10),
               type_=mysql.ENUM('kg, lbs'),
               existing_nullable=False)

    # ### end Alembic commands ###
