"""added foreign key to equipment

Revision ID: 6bbc794bf754
Revises: 7fd926107b5e
Create Date: 2025-03-12 13:55:22.177893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bbc794bf754'
down_revision = '7fd926107b5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'exercise', ['exercise_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exercise_id')

    # ### end Alembic commands ###
